### ISSUE TITLE
tests in master branch are erroring out 'CONFIG_FILE' is not recognized error

### ISSUE THREAD

**Issue by spnraju** [browserstack/cucumber-js-browserstack#14]
Hi there,

I cloned this repo as is. done npm i and tried running the script using 'npm run single' and 'npm run local'. Both the times, it gave me error as below.

![image](https://user-images.githubusercontent.com/33729221/53998681-9abc1d80-4166-11e9-8432-ce8bf24b110a.png)

Please let me know what is that I am missing.

I am on Windows 10

**Comment by Varun-garg** [comment]
It is an issue while setting environment variables from `package.json` on windows 10. Could you try this out?

**Comment by pulkitsharma07** [comment]
Thanks for raising this issue @spnraju, can you try running the tests again.
